# Generated by Django 4.2 on 2024-06-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, default='defaults/avengers.jpg', null=True, upload_to='images/'),
        ),
    ]
