# Generated by Django 5.0.6 on 2024-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField()),
                ('room_discription', models.TextField()),
                ('room_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
